INSERT INTO `events` (`curtain_id`, `event_position`, `event_time`) VALUES
(1, 450, CURRENT_DATE - INTERVAL 7 DAY + INTERVAL 8 HOUR),
(1, 350, CURRENT_DATE - INTERVAL 14 DAY + INTERVAL 8 HOUR + INTERVAL 20 MINUTE),
(1, 500, CURRENT_DATE - INTERVAL 21 DAY + INTERVAL 7 HOUR + INTERVAL 40 MINUTE);


INSERT INTO `events` (`curtain_id`, `event_position`, `event_time`) VALUES
(1, 1000, CURRENT_DATE - INTERVAL 7 DAY + INTERVAL 12 HOUR),
(1, 900, CURRENT_DATE - INTERVAL 14 DAY + INTERVAL 12 HOUR + INTERVAL 20 MINUTE),
(1, 950, CURRENT_DATE - INTERVAL 21 DAY + INTERVAL 11 HOUR + INTERVAL 40 MINUTE),
(1, 850, CURRENT_DATE - INTERVAL 21 DAY + INTERVAL 12 HOUR + INTERVAL 30 MINUTE);


INSERT INTO `events` (`curtain_id`, `event_position`, `event_time`) VALUES
(1, 0, CURRENT_DATE - INTERVAL 7 DAY + INTERVAL 19 HOUR),
(1, 0, CURRENT_DATE - INTERVAL 14 DAY + INTERVAL 19 HOUR + INTERVAL 20 MINUTE),
(1, 0, CURRENT_DATE - INTERVAL 21 DAY + INTERVAL 18 HOUR + INTERVAL 40 MINUTE),
(1, 0, CURRENT_DATE - INTERVAL 21 DAY + INTERVAL 19 HOUR + INTERVAL 30 MINUTE);